### ISSUE TITLE
Compatibility with Labkey 22.3.2

### ISSUE THREAD

**Issue by johannpellet** [BimberLab/DiscvrLabKeyModules#151]
Hi,
I tried to install DISCVR  21.7 to Labkey Server Community 22.3.2 but it was not compatible. I also tried to use only modules for DISCVR-seq only (laboratory, ldk and sequenceanalysis) but it was the same.

Will it be possible in the future to use DISCVR with this version of Labkey?

Regards,
Johann

**Comment by bbimber** [comment]
Yes, you need a 22.3 version.  Because of how we develop there is essentially always a version compatible with the current LabKey; however, it wouldnt be obvious to get. I kicked off a new release for 22.3 and the build should appear on github to download within an hour or so.

**Comment by bbimber** [comment]
this has been up for a few days. please let me know if you have questions or issues.
