### ISSUE TITLE
Create and host a minimal plugin for testing purposes

### ISSUE THREAD

**Issue by jctrotter** [BimberLab/DiscvrLabKeyModules#39]
Task 2:
- Host plugin from LK server
- Host plugin json+code either in ./resources/jbrowse/plugins (if no build needed), or in ./src/client/XXXX if we need to build code
- Update minimalSession.json to include plugin config (note: this might need to update server URL)
- Make the demo plugin do something really obvious
- Create test that verifies this plugin is loaded

**Comment by bbimber** [comment]
We need to figure out soon whether the plugin will be simple JS, or whether it needs to be built. 

See the patch I sent earlier for a crude example of where the relevant files would live in the module, and how one might update URLs in minimalSession.json.
