### ISSUE TITLE
Selenium Testing

### ISSUE THREAD

**Issue by jctrotter** [BimberLab/DiscvrLabKeyModules#42]
Task 5

**Comment by bbimber** [comment]
I sent a patch with changes to the existing JBrowseTest selenium code. This is a good base. It will create a demo project and ultimately load data into it. 

For the purpose of this task, we should make an integration test that loads our demo session UI and clicks around to verify it's working as we expect. I would do these steps:

- beginAt() the demo page
- click the button to load the data
- navigate to 1:118,884,813..118,884,813 (or a larger window)
- click to load the VCF track
- wait until it loads (maybe looking for a CSS based on variant squares
- click the variant at 1:118,884,813..118,884,813
- verify some things about the popup

That's probably good enough for this phase. See here for info on running tests:

https://www.labkey.org/Documentation/wiki-page.view?name=runningTests

 ./gradlew :server:test:uiTests

When you start doing this, let's meet to talk about some efficient ways to write/execute them. One big time saver is to:

- Dont repeat the setup when re-running
**- Put a breakpoint immediately before the section you're developing. You can use the intellij watch window to basically write your test, line-by-line, interactively. This is orders of magnitude more efficient than writing code, running, hitting a problem, and then doing this over again**
